### ISSUE TITLE
Наладить взаимодействие с ботом в MS Teams

### ISSUE THREAD

**Issue by RuslanOm** [5000factorial/feedback-service#19]

**Comment by sevryukov** [comment]
В чём состояла задача, какие у неё результаты?

**Comment by RuslanOm** [comment]
Задача состояла в том, чтобы интегрировать систему опросов в MS Teams посредством бота, который бы по окончании занятия рассылал ссылки на опросы участникам канала. Однако, было выявлено, что такое автоматизированное поведение со стороны ботов в MS Teams не предусмотрено. 

Изначально планировался следующий сценарий взаимодействия: бот подписывается на какое-то событие в канале (например, на запланированное собрание). Затем, когда это событие произошло (собрание закончилось), бот рассылает участникам собрания ссылки на опросы, и те их проходят. Но в MS Teams нет такой функциональности у ботов, т.е. чтобы бот что-то сделал, его нужно явно упомянуть в сообщении канала. После этого бот уже может выполнить в ответ на это обращение заложенные в нем действия (разослать ссылки на опросы). Однако, такой сценарий накладывает дополнительные обязательства на преподавателей: они должны не забыть после занятия отправить сообщение боту, чтобы тот отправил ссылки. Это может повлечь нарушение периодичности проведения опросов и тем самым снизить пользу от анкетирования. В связи с этим командой было принято решение заменить бота на интегрированную вкладку в MS Teams. Достоинством данного решения является то, что теперь вкладка с опросом доступна студенту в любой момент, и он может пройти опрос в удобное для него время. Также, этот сценарий исключает те случаи, когда опрос не был пройден студентом по какой-либо внешней причине - теперь это полностью на совести студента.

**Comment by sevryukov** [comment]
На основании какой документации или эксперимента был сделан вывод о том, что бот не может инициировать беседу?

https://docs.microsoft.com/ru-ru/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conv-proactive

**Comment by itonik** [comment]
@sevryukov не может инициировать беседу в канале, только в личных сообщениях

**Comment by sevryukov** [comment]
@itonik а зачем в канале и опять же, где пруф?
